### PR TITLE
Made minor changes to the controller to clean up the logic. Still need to simplify the first always block.

### PR DESCRIPTION
**Pull request by JacobPease**

### CODE REVIEW

**Comment by JacobPease** [comment]
Weird. I just changed this file after pulling. I'll look into it.

**Comment by jordancarlin** [comment]
Pretty sure it was a lint_off issue that I fixed. Should be an easy resolution.

**Comment by jordancarlin** [comment]
You seem to have accidentally reverted other recent PRs when fixing the merge conflict...

**Comment by rosethompson** [comment]
We should try to get this merged. I'm a bit confused by the commit history. It shows many extra files changed?  Is the best way to merge to swash into a single commit so we don't have the unnecessary changes in the history?

**Comment by jordancarlin** [comment]
I only see 2 files being changed...

**Comment by rosethompson** [comment]
It's more the history has a bunch of files bunch of file changed. Maybe that's ok.

**Comment by jordancarlin** [comment]
I think those were all force pushed away. Looking through the 3 commits that are actually included in the PR I don't see any extra files being modified. If we're worried about it though then squash merging should be fine. @JacobPease would just need to hard reset his branch afterwards.

**Comment by rosethompson** [comment]
I think we can just merge the pr.

**Pull request merged**
