### PR TITLE
Removed source.sh dependency in nightly build

### PR DESCRIPTION
**Pull request by slmnemo**

### CODE REVIEW

**Comment by slmnemo** [comment]
Don't merge this yet, found some kind of bug with rv64gc coverage64gc I'd like to talk to someone about

**Comment by jordancarlin** [comment]
@slmnemo seems to be a merge issue again. Lots of previous commits are duplicated.

**Comment by slmnemo** [comment]
shoot :(

**Comment by slmnemo** [comment]
remade the PR

**Comment by slmnemo** [comment]
https://github.com/openhwgroup/cvw/pull/1057

**Pull request closed without merging**
