### PR TITLE
Fixing order of local repo commands in README

### PR DESCRIPTION
**Pull request by magpyed**
Very minor edit to README to make the given setup code for local git repositories work as intended.

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @magpyed, thanks for your interest in cvw!   Before we can accept your pull-request, you need to be covered by the `Eclipse Contributor Agreement`.  Fortunately, this is (mostly) painless - see [CONTRIBUTING](https://github.com/openhwgroup/cvw/blob/main/CONTRIBUTING.md) for the details.

**Comment by ross144** [comment]
Hi Lim. The contributor agreement is really easy to setup.

1. You need to create an account with https://www.eclipse.org/
2. Sign the agreement, https://www.eclipse.org/legal/ECA.php
3. Use Harvey Mudd College as your Employer

**Comment by magpyed** [comment]
Thanks Ross! I've done the contributor agreement setup, is there an easy way to have the branch rechecked? I can push some more minor changes (like typo fixes) if that's a good solution.

**Comment by ross144** [comment]
HI Lim.  You're all good now.  We'll merge your pr.

**Comment by MikeOpenHWGroup** [comment]
Thanks for playing ball @magpyed!  It's important to get the "legal stuff" right.

**Pull request merged**
