### PR TITLE
Modified riscv-isacov and riscv-ctg files to support some missing quad instructions.

### PR DESCRIPTION
**Pull request by Shreesh-Kulkarni**
Some of the files in ISACOV and CTG were missing some quad instructions and FLEN support. These updated files fix that. Will be helpful once additional opcodes are included in the Quad suite.

### CODE REVIEW

**Comment by Shreesh-Kulkarni** [comment]
I will be adding/committing more files here if I have missed anything. Will update on when the PR can be merged.

**Comment by davidharrishmc** [comment]
This is good stuff!  Let me know when you want it merged.

**Comment by davidharrishmc** [comment]
@Shreesh-Kulkarni do you want us to merge this PR?

**Comment by Shreesh-Kulkarni** [comment]
@davidharrishmc Yes, the PR is ready to be merged. I will submit more PRs this weekend for additional opcodes. Was busy with work hence took me some time.

**Pull request merged**
