### PR TITLE
Pmpcfg new test cases

### PR DESCRIPTION
**Pull request by liamchalk00**
Here is an updated pull request on behalf of koooo142857 (Kevin) and myself for adding new test cases for pmpcfg.
Tests around 40% of the pmpcfg logic for locking pmpaddr by writing to pmp0cfg-pmp15cfg fields within the pmpcfg0 and pmpcfg2 registers.

### CODE REVIEW

**Comment by ross144** [comment]
Hi Liam,  

Before you can commit to an openhwgroup repo you have to sign the Eclipse contributor agreement. It is really easy to do.

1.     You need to create an account with https://www.eclipse.org/
2.     Sign the agreement, https://www.eclipse.org/legal/ECA.php
3.     Use Harvey Mudd College as your Employer

**Comment by ross144** [comment]
Does this PR supersede Kevin's or do we need to merge both?

**Comment by liamchalk00** [comment]
Hi Ross,

Previously I had student checked for employer, now I have changed it to other and filled in Harvey Mudd College. I then resigned the ECA agreement.

This PR supersedes Kevin's PR.

This pull request still says 'All checks have failed.' Should Eclipse update my access permission for this PR or do I need to create a new PR?

Thanks,
Liam

**Comment by ross144** [comment]
Hmm. I wonder what the issue is then.  Can you check your email address listed in the commit
`
From: =?UTF-8?q?Liam=20Chalk=E2=80=B3?= <″lchalk@hmc.edu″>`
matches the email used to sign the ECA?

**Pull request closed without merging**
