### PR TITLE
Update riscv-arch-test

### LINKED ISSUE #783: Use riscv-arch-test tests instead of wally-riscv-arch-test for Zfa

### PR DESCRIPTION
**Pull request by jordancarlin**
- Update riscv-arch-test submodule and target dev branch
- Remove Zfa wally-riscv-arch-test and replace with tests from riscv-arch-test
- Update f_fma tests to use the new, smaller test files

Closes #783

### CODE REVIEW

**Comment by davidharrishmc** [comment]
Jordan, the new riscv-arch-test repo had split the fma _b15 tests into several thousand tiny subfiles (~300 per instruction per precision).  Our tests.vh only runs the -01 subfile, which is now 1/300th of the total set of tests.

https://github.com/riscv-non-isa/riscv-arch-test/tree/main/riscv-test-suite/rv32i_m/F/src

I've requested a smaller number of subfiles.

https://github.com/riscv-non-isa/riscv-arch-test/pull/461#issuecomment-2088313884

I can't move to the new riscv-arch-test repo without doing something, or I'll lose all these fma tests.  I've been waiting on this until they make a decision.  

Thanks for preparing this PR.  Let's hold off on accepting it until riscv-arch-test makes a decision.

**Comment by jordancarlin** [comment]
Oh. I totally missed that. I saw that the issue preventing Zfa tests from working was resolved so figured I’d switch over, but let’s definitely wait on restructuring tests.vh until the fma tests settle.

**Comment by davidharrishmc** [comment]
fma looks like it has settled.  There are now subdirectories in riscv-arch-test with the FMA tests split into 50 parts each, which is reasonable.

@jordancarlin do you have bandwidth to incorporate those into riscv-arch-test as well, test it out, and update the PR with fma as well as Zfa?

**Comment by jordancarlin** [comment]
I saw that update a little while ago, but it looks like it’s just on the dev branch for now. Would we rather wait for the next release with these changes or switch our submodule to target the dev branch?On Jun 11, 2024, at 7:24 AM, David Harris ***@***.***> wrote:﻿
fma looks like it has settled.  There are now subdirectories in riscv-arch-test with the FMA tests split into 50 parts each, which is reasonable.
@jordancarlin do you have bandwidth to incorporate those fma tests into tests.vh as well, test it out, and update the PR with fma as well as Zfa?

**Comment by davidharrishmc** [comment]
Good catch.  Let’s wait.  Feel free to ask Umer if there is a schedule to upstream this change.

**Comment by jordancarlin** [comment]
@davidharrishmc Many of the b15 fma tests are currently commented out. Do we want to reenable them? Only the b15 tests for F were split into smaller files, D and Zfh currently remain as they were.

**Pull request merged**
