### PR TITLE
SSTC

### PR DESCRIPTION
**Pull request by davidharrishmc**
Implemented supervisor timer compare.  Tests aren't updated to use it yet, so feature is disabled in rv32gc and rv64gc.

### CODE REVIEW

**Comment by ross144** [comment]
@MikeOpenHWGroup.  For some reason the old commit in David's PR is failing the author check.  However the commit author email address is the same for all commits.  Any idea why this is happening?

**Comment by DBees** [comment]
Not sure what is happening there with the EF validation. Have opened an EF helpdesk issue
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2698

**Comment by MikeOpenHWGroup** [comment]
Hi @davidharrishmc and @ross144.

The ECA check is failing because at least one commit on this pull-request is from an account that is not covered by the ECA.  For security reasons, the Eclipse Foundation tools will not show me the full email address, but I know it is of the form `david_harris@****.edu`.  The email address that is covered by your ECA is of the form `davidharrishmc@****.****.****.com`.

There are two solutions:
1. Rebase your code to replace the submitter for the "bad" commit.  There is a HOWTO in the core-v-verif `GitCheats` [here](https://github.com/openhwgroup/core-v-verif/blob/master/GitCheats.md#rebasing-a-previous-commit).
2. Close the offending PR and start again.

Both will work, option 1 is preferred by git purest, but it gets awful close to the edge of my "git confidence threshold".  Non-linear outcomes result from exceeding that threshold.

**Comment by davidharrishmc** [comment]
I don't understand the ECA check issue.  

I see three different types of marks: a red x, a green verified, and a blank spot.  The red x are all associated with commits from david_harris@***.edu.  The green verified are all associated with commits from ***+davidharrishmc@users.noreply.github.com.  The blank entries are also associated with david_harris@***.edu.

I don't understand why some of the david_harris@***.edu are marked blank and some have an x.  This is the address that I normally use. It seems like certain ones are randomly breaking.

I'm also not sure what causes certain commits to come from davidharrishmc.

**Comment by stineje** [comment]
Mike,

The ECA issue I had was related to not picking up my name from the push.  I tried, and tried, to fix it but I couldn’t.  Luckily, Ross was able to delete it somehow and I managed to reconfigure my Email/Name and then it worked.  I even tried to re-sign the ECA but it wouldn’t accept it because my Email was wrong.  There seems to be a bug in the process.  Just FYI.

All my best,

James

**Comment by MikeOpenHWGroup** [comment]
Thanks for the feedback.  I'll look into this with @DBees and get back to you.

**Comment by davidharrishmc** [comment]
I've concluded that the problem is a bug in the ECA check and not a lack of signed Eclipse agreement.  Some of the commits with my david_harris@xxx.edu email pass the check and some fail.  I'm taking the PR despite the check failing.

**Comment by ross144** [comment]
I am not a fan of squashing these into a single commit.  And we need to merge this pull request so we can continue to make progress.  Since this appears to be an internal issue I am going to accept the changes.

**Pull request merged**
