### PR TITLE
fp-testbench does not stop on error now

### PR DESCRIPTION
**Pull request by kevindkim723**

### CODE REVIEW

**Review by stineje — COMMENTED** [review]
looks like removal of $stop - wouldn't it be better to $stop on an error.  Perhaps, we can add a feature to testfloat.do to check and stop if needed.  I can make this change in about 60sec if you want this.

**Comment by ross144** [comment]
I like that idea.

**Comment by stineje** [comment]
Made new PR to help avoid this issue - kevindkim723: if this is okay, you can cancel this PR.

**Comment by davidharrishmc** [comment]
Kevin, just comment out the stop in your local version while you need to run past first error.  Let's leave the stop in the repository.

**Pull request closed without merging**
