### PR TITLE
Added Zcf & Zcd in rv32/64gc

### PR DESCRIPTION
**Pull request by Zain2050**

### CODE REVIEW

**Comment by davidharrishmc** [comment]
Might as well enable Zcd in 32 and 64 while you are at it, even if we don't have coverage yet.

**Comment by davidharrishmc** [comment]
These covergroups aren't showing up in my report yet.  @Zain2050 is there anything else you need to push?

**Comment by Zain2050** [comment]
That's strange. Both Zcf & Zcd are showing up in my report. I'll check if I missed something.

**Comment by Zain2050** [comment]
These were the only changes I made. Everything seems to be working fine on my side.
I'll ask my team members if they are getting coverage or not.

**Comment by Mysterio-Abdullah** [comment]
I'm also having the coverage for both Zcf and Zcd now. Everything seems to be working fine on my side too.

**Comment by davidharrishmc** [comment]
Hmm.  They are showing up for me now too.  Maybe I didn't pull this properly yesterday.  All is good now.

**Comment by Zain2050** [comment]
Great!

**Pull request merged**
