### PR TITLE
Fetch buffer passes regression!

### PR DESCRIPTION
**Pull request by jordancarlin**
Update hazards and reset value so fetch_buffer passes regression.

### CODE REVIEW

**Comment by davidharrishmc** [comment]
Is this supposed to change 159 files?

**Comment by jordancarlin** [comment]
It is also updating the fetch buffer branch with all of the changes from the main branch, so yes. If you'd rather I can do that as a separate PR.

The actual changes are all in the last commit if you want to look at them.

**Comment by davidharrishmc** [comment]
Let's do a review at the research group meeting.

**Comment by jordancarlin** [comment]
Sounds good. I will open another PR in the meantime to update the fetch_buffer branch so this is easier to review.

**Comment by rosethompson** [comment]
I don't think I can make it to your review later today, but I have some comments about the fetch buffer.
1. I like very simple design of the fetch buffer and how it decouples the fetch stage stalls from the rest of the pipeline.
2. Is there a way to simplify the spill logic? Specifically it looks like the spills are unchanged so a 4 byte spill across two cache lines will still cause a spill delay.  Are we still paying the extra cycle of latency? If so how difficult will it be to move the spill logic after the fetch buffer so it can absorb the cycle?
I am very pleased with the simplicity of the design.

**Comment by jordancarlin** [comment]
Thanks @rosethompson.

The goal is definitely to modify the spill logic. We wanted to get the minimal viable version working first and then begin optimizing from there. Right now there is no performance benefit from the fetch buffer. Avoiding the latency for spills if the second instruction is already in the buffer is one of the big optimizations we want to make. Several other stalls can also probably be eliminated.

**Comment by rosethompson** [comment]
I thought that might be the case. I approve of these changes and I look forward to the future!

**Pull request merged**
