### PR TITLE
Integrated tv generation for IFdivsqrt

### PR DESCRIPTION
**Pull request by amaiuolo**
The changes don't affect the current setup. One would still have to uncomment line 8 in create_all_vectors.sh to se any change in functionality. These test vectors will be used for our intdiv paper when talking about the various benefits of combined IFdivsqrt. In addition to the two lines of comment code to create_all_vectors.sh, there is a folder added in tests/fp called combined_IF_vectors that contains all my additions.

### CODE REVIEW

**Comment by ross144** [comment]
Hi Alessandro, before you can commit requests to open hardware you need to fill out the Eclipse Contributor Agreement (ECA).
1. You need to create an account with https://www.eclipse.org/
2. Sign the agreement, https://www.eclipse.org/legal/ECA.php
3. Use Harvey Mudd College as your Employer

**Comment by amaiuolo** [comment]
Sounds good. I’ll get on that asap.

- Alessandro

**Comment by amaiuolo** [comment]
Good morning,

I completed the ECA and now the repo says “all checks have passed,” so the PR should be good to go?

Best!
Alessandro

**Comment by davidharrishmc** [comment]
Whoo!  Merged!

**Pull request merged**
